---
name: paasta-ci
on: [push, release]
jobs:
  tox:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        toxenv:
          - py37-linux,docs,mypy,tests
          - general_itests
          - paasta_itests
          - example_cluster
    env:
      PIP_INDEX_URL: https://pypi.python.org/simple
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: python -m pip install --upgrade pip
      - run: pip install coveralls tox==3.2 tox-pip-extensions==1.3.0 ephemeral-port-reserve
      - run: tox -i https://pypi.python.org/simple -e ${{ matrix.toxenv }}
  k8s_itests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: python -m pip install --upgrade pip virtualenv
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run: python -m pip install --upgrade pip
      - run: pip install coveralls tox==3.2 tox-pip-extensions==1.3.0 ephemeral-port-reserve
      - run: make k8s_itests
  build_debs:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        dist: [xenial, bionic, focal]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: sudo apt-get install -yq devscripts
      - run: make itest_${{ matrix.dist }}
      - run: "echo -n ::set-output name=package_name::; echo ./dist/paasta-tools_*.deb"
        id: get_package_name
      - run: "echo -n ::set-output name=version::; dpkg-parsechangelog -l./debian/changelog | sed -n 's/^Version: //p'"
        id: get_version
      - name: Upload deb package to Bintray
        if: github.event_name == 'release'
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: ${{ steps.get_package_name.outputs.package_name }}
          api_user: yelptravis
          api_key: ${{ secrets.BINTRAY_API_KEY }}
          repository_user: yelp
          repository: paasta
          package: paasta-tools
          version: ${{ steps.get_version.outputs.version }}
          upload_path: dists/${{ matrix.dist }}/main
          publish: 1
          calculate_metadata: true
          deb_distribution: ${{ matrix.dist }}
          deb_component: main
          deb_architecture: amd64
